- test_name: 'integ_rn_ios_storage'
  working_directory: amplify-js-samples-staging/samples/react-native/storage/StorageApp
  timeout_minutes: 120
- test_name: 'integ_rn_ios_storage_multipart_progress'
  working_directory: amplify-js-samples-staging/samples/react-native/storage/MultiPartUploadWithProgress
  timeout_minutes: 120
- test_name: 'integ_rn_ios_device_tracking'
  working_directory: amplify-js-samples-staging/samples/react-native/auth/deviceTracking
  timeout_minutes: 120
- test_name: 'integ_rn_ios_datastore_sqlite_adapter'
  working_directory: amplify-js-samples-staging/samples/react-native/datastore/SQLiteAdapter
  timeout_minutes: 120
- test_name: 'integ_rn_ios_api_gen2_rn_72_detox_cli'
  working_directory: amplify-js-samples-staging/samples/react-native/api/gen2/ApiGraphQLGen2
  timeout_minutes: 120
- test_name: 'integ_rn_ios_api_v6_rn_72_detox_cli'
  working_directory: amplify-js-samples-staging/samples/react-native/api/v6/ApiGRAPHQL
  timeout_minutes: 120
- test_name: 'integ_rn_ios_oidc_signout'
  working_directory: amplify-js-samples-staging/samples/react-native/auth/HosteduiApp
  timeout_minutes: 120
  host_signout_page: true
