- test_name: 'integ_rn_ios_storage'
  working_directory: amplify-js-samples-staging/samples/react-native/storage/StorageApp
- test_name: 'integ_rn_ios_storage_multipart_progress'
  working_directory: amplify-js-samples-staging/samples/react-native/storage/MultiPartUploadWithProgress
- test_name: 'integ_rn_ios_device_tracking'
  working_directory: amplify-js-samples-staging/samples/react-native/auth/deviceTracking
  timeout_minutes: 120
- test_name: 'integ_rn_ios_datastore_sqlite_adapter'
  working_directory: amplify-js-samples-staging/samples/react-native/datastore/SQLiteAdapter
# - test_name: 'integ_rn_android_storage'
#   working_directory: ~/amplify-js-samples-staging/samples/react-native/storage/StorageApp
# - test_name: 'integ_rn_android_storage_multipart_progress'
#   working_directory: ~/amplify-js-samples-staging/samples/react-native/storage/MultiPartUploadWithProgress
