minimal_browser_list: &minimal_browser_list
  - chrome

tests:
  # DataStore tests
  - test_name: integ_next_datastore_owner_auth
    desc: 'next owner auth'
    framework: next
    category: datastore
    sample_name: [owner-based-default]
    spec: next-owner-based-default
    browser: *minimal_browser_list
  - test_name: integ_next_datastore_13_basic
    desc: 'DataStore - Nextjs 13 build with SWC - basic JS app'
    framework: next
    category: datastore
    sample_name: [next-13-basic]
    spec: nextjs-13-basic
    browser: *minimal_browser_list
  - test_name: integ_next_datastore_13_js
    desc: 'DataStore - Nextjs 13 build with SWC - JS app'
    framework: next
    category: datastore
    sample_name: [next-13-js]
    spec: nextjs-13
    browser: *minimal_browser_list
  
  # Auth tests
  - test_name: integ_next_auth_authenticator_and_ssr_page
    desc: 'Authenticator and SSR page'
    framework: next
    category: auth
    sample_name: [auth-ssr]
    spec: auth-ssr
    browser: *minimal_browser_list
  - test_name: integ_next_auth_authenticator_and_rsc_page
    desc: 'Authenticator and RSC page'
    framework: next
    category: auth
    sample_name: [auth-rsc]
    spec: auth-rsc
    browser: [chrome]
    timeout_minutes: 45
    retry_count: 10
  - test_name: integ_next_auth_nextjs_auth_custom_implementation_with_ssr
    desc: 'NextJS Auth Custom Implementation with SSR'
    framework: next
    category: auth
    sample_name: [custom-auth-ssr]
    spec: authenticator
    browser: *minimal_browser_list
