tests:
  # SSR context isolation
  - test_name: integ_ssr_context_isolation
    desc: 'SSR Context Isolation'
    framework: next
    category: ssr-adapter
    sample_name: ssr-context-isolation
    spec: ssr-context-isolation
