minimal_browser_list: &minimal_browser_list
  - chrome
  - firefox

extended_browser_list: &extended_browser_list
  - chrome
  - firefox
  - edge

tests:
  - test_name: subdomain_authentication
    desc: 'Sign-in with the OAuth flow and subdomains'
    framework: next
    category: auth
    sample_name: [subdomains]
    spec: subdomains
    browser: [chrome]
