minimal_browser_list: &minimal_browser_list
  - chrome
  - firefox

extended_browser_list: &extended_browser_list
  - chrome
  - firefox
  - edge

tests:
  # AUTH GEN2
  - test_name: integ_next_sign_in_with_oauth_gen2
    desc: "Sign-in with the OAuth flow"
    framework: next
    category: auth
    sample_name: [sign-in-with-oauth]
    spec: sign-in-with-oauth
    browser: [chrome]
    backend: gen2
  - test_name: integ_vue_sign_in_with_oauth_gen2
    desc: "Sign-in with the OAuth flow"
    framework: vue
    category: auth
    sample_name: [sign-in-with-oauth]
    spec: sign-in-with-oauth
    browser: [chrome]
