export declare const Container: {};
export declare const FormContainer: {};
export declare const FormSection: {};
export declare const FormField: {};
export declare const SectionHeader: {};
export declare const SectionBody: {};
export declare const SectionFooter: {};
export declare const SectionFooterPrimaryContent: {};
export declare const SectionFooterSecondaryContent: {};
export declare const Input: {};
export declare const Button: {};
export declare const PhotoPickerButton: {};
export declare const PhotoPlaceholder: {};
export declare const SignInButton: {};
export declare const SignInButtonIcon: {};
export declare const SignInButtonContent: {};
export declare const Strike: {};
export declare const StrikeContent: {};
export declare const ActionRow: {};
export declare const FormRow: {};
export declare const A: {};
export declare const Hint: {};
export declare const Radio: {};
export declare const Label: {};
export declare const InputLabel: {};
export declare const AmazonSignInButton: {};
export declare const FacebookSignInButton: {};
export declare const GoogleSignInButton: {};
export declare const OAuthSignInButton: {};
export declare const Toast: {};
export declare const NavBar: {};
export declare const NavRight: {};
export declare const Nav: {};
export declare const NavItem: {};
export declare const NavButton: {};
declare const AmplifyTheme: {
	container: {};
	formContainer: {};
	formSection: {};
	formField: {};
	sectionHeader: {};
	sectionBody: {};
	sectionFooter: {};
	sectionFooterPrimaryContent: {};
	sectionFooterSecondaryContent: {};
	input: {};
	button: {};
	photoPickerButton: {};
	photoPlaceholder: {};
	signInButton: {};
	signInButtonIcon: {};
	signInButtonContent: {};
	amazonSignInButton: {};
	facebookSignInButton: {};
	googleSignInButton: {};
	oAuthSignInButton: {};
	formRow: {};
	strike: {};
	strikeContent: {};
	actionRow: {};
	a: {};
	hint: {};
	radio: {};
	label: {};
	inputLabel: {};
	toast: {};
	navBar: {};
	nav: {};
	navRight: {};
	navItem: {};
	navButton: {};
};
export default AmplifyTheme;
