import '@aws-amplify/ui/dist/style.css';
export declare const Container: (props: any) => any;
export declare const FormContainer: (props: any) => any;
export declare const FormSection: (props: any) => JSX.Element;
export declare const SectionHeader: (props: any) => any;
export declare const SectionHeaderContent: (props: any) => any;
export declare const SectionFooter: (props: any) => any;
export declare const SectionFooterPrimaryContent: (props: any) => any;
export declare const SectionFooterSecondaryContent: (props: any) => any;
export declare const SectionBody: (props: any) => any;
export declare const ActionRow: (props: any) => any;
export declare const Strike: (props: any) => any;
export declare const StrikeContent: (props: any) => any;
export declare const FormRow: (props: any) => any;
export declare const RadioRow: (props: any) => JSX.Element;
export declare const Radio: (props: any) => any;
export declare const InputRow: (props: any) => JSX.Element;
export declare const Input: (props: any) => JSX.Element;
export declare const SelectInput: (props: any) => JSX.Element;
export declare const FormField: (props: any) => any;
export declare const Button: (props: any) => any;
export declare const PhotoPickerButton: (props: any) => JSX.Element;
export declare const SignInButton: (props: any) => any;
export declare const SignInButtonIcon: (props: any) => any;
export declare const SignInButtonContent: (props: any) => any;
export declare const Link: (props: any) => any;
export declare const Label: (props: any) => any;
export declare const Hint: (props: any) => any;
export declare const InputLabel: (props: any) => any;
export declare const NavBar: (props: any) => any;
export declare const Nav: (props: any) => any;
export declare const NavRight: (props: any) => any;
export declare const NavItem: (props: any) => any;
export declare const NavButton: (props: any) => any;
export declare const Toast: {
	(props: any): JSX.Element;
	defaultProps: {
		onClose: () => any;
	};
};
export declare const PhotoPlaceholder: (props: any) => JSX.Element;
export declare const beforeAfter: (el: any) => any;
export declare const propStyle: (props: any, themeStyle: any) => any;
