import { NgModule } from '@angular/core';
import { defineCustomElements } from '@aws-amplify/ui-components/loader';

import {
	AmplifyAuthenticator,
	AmplifySignIn,
	AmplifySignUp,
	AmplifySignOut,
	AmplifyConfirmSignIn,
	AmplifyConfirmSignUp,
	AmplifyForgotPassword,
	AmplifyRequireNewPassword,
	AmplifyVerifyContact,
	AmplifyTotpSetup,
	AmplifyAmazonButton,
	AmplifyAuthFields,
	AmplifyAuth0Button,
	AmplifyButton,
	AmplifyCheckbox,
	AmplifyCodeField,
	AmplifyCountryDialCode,
	AmplifyEmailField,
	AmplifyFacebookButton,
	AmplifyFederatedButtons,
	AmplifyFederatedSignIn,
	AmplifyFormField,
	AmplifyFormSection,
	AmplifyGoogleButton,
	AmplifyGreetings,
	AmplifyHint,
	AmplifyIcon,
	AmplifyIconButton,
	AmplifyInput,
	AmplifyLabel,
	AmplifyLink,
	AmplifyLoadingSpinner,
	AmplifyNav,
	AmplifyOauthButton,
	AmplifyPasswordField,
	AmplifyPhoneField,
	AmplifyRadioButton,
	AmplifySection,
	AmplifySelect,
	AmplifySelectMfaType,
	AmplifySignInButton,
	AmplifyStrike,
	AmplifyToast,
	AmplifyTooltip,
	AmplifyUsernameField,
} from './directives/proxies';

defineCustomElements(window);

const DECLARATIONS = [
	AmplifyAuthenticator,
	AmplifySignIn,
	AmplifySignUp,
	AmplifySignOut,
	AmplifyConfirmSignIn,
	AmplifyConfirmSignUp,
	AmplifyForgotPassword,
	AmplifyRequireNewPassword,
	AmplifyVerifyContact,
	AmplifyTotpSetup,
	AmplifyAmazonButton,
	AmplifyAuthFields,
	AmplifyAuth0Button,
	AmplifyButton,
	AmplifyCheckbox,
	AmplifyCodeField,
	AmplifyCountryDialCode,
	AmplifyEmailField,
	AmplifyFacebookButton,
	AmplifyFederatedButtons,
	AmplifyFederatedSignIn,
	AmplifyFormField,
	AmplifyFormSection,
	AmplifyGoogleButton,
	AmplifyGreetings,
	AmplifyHint,
	AmplifyIcon,
	AmplifyIconButton,
	AmplifyInput,
	AmplifyLabel,
	AmplifyLink,
	AmplifyLoadingSpinner,
	AmplifyNav,
	AmplifyOauthButton,
	AmplifyPasswordField,
	AmplifyPhoneField,
	AmplifyRadioButton,
	AmplifySection,
	AmplifySelect,
	AmplifySelectMfaType,
	AmplifySignInButton,
	AmplifyStrike,
	AmplifyToast,
	AmplifyTooltip,
	AmplifyUsernameField,
];

@NgModule({
	declarations: DECLARATIONS,
	exports: DECLARATIONS,
	imports: [],
	providers: [],
})
export class AmplifyUIAngularModule { }
