import { NgModule } from '@angular/core';
import { defineCustomElements } from '@aws-amplify/ui-components/loader';

import {
	AmplifyAmazonButton,
	AmplifyAuth0Button,
	AmplifyAuthenticator,
	AmplifyAuthContainer,
	AmplifyAuthFields,
	AmplifyButton,
	AmplifyChatbot,
	AmplifyCheckbox,
	AmplifyCodeField,
	AmplifyConfirmSignIn,
	AmplifyConfirmSignUp,
	AmplifyContainer,
	AmplifyCountryDialCode,
	AmplifyEmailField,
	AmplifyFacebookButton,
	AmplifyFederatedButtons,
	AmplifyFederatedSignIn,
	AmplifyForgotPassword,
	AmplifyFormField,
	AmplifyFormSection,
	AmplifyGoogleButton,
	AmplifyGreetings,
	AmplifyHint,
	AmplifyIcon,
	AmplifyIconButton,
	AmplifyInput,
	AmplifyLabel,
	AmplifyLink,
	AmplifyLoadingSpinner,
	AmplifyNav,
	AmplifyOauthButton,
	AmplifyPasswordField,
	AmplifyPhoneField,
	AmplifyPhotoPicker,
	AmplifyPicker,
	AmplifyRadioButton,
	AmplifyRequireNewPassword,
	AmplifyS3Album,
	AmplifyS3Image,
	AmplifyS3ImagePicker,
	AmplifyS3Text,
	AmplifyS3TextPicker,
	AmplifySection,
	AmplifySelect,
	AmplifySelectMfaType,
	AmplifySignIn,
	AmplifySignInButton,
	AmplifySignOut,
	AmplifySignUp,
	AmplifyStrike,
	AmplifyToast,
	AmplifyTooltip,
	AmplifyTotpSetup,
	AmplifyUsernameField,
	AmplifyVerifyContact,
} from './directives/proxies';

defineCustomElements(window);

const DECLARATIONS = [
	AmplifyAmazonButton,
	AmplifyAuth0Button,
	AmplifyAuthenticator,
	AmplifyAuthContainer,
	AmplifyAuthFields,
	AmplifyButton,
	AmplifyChatbot,
	AmplifyCheckbox,
	AmplifyCodeField,
	AmplifyConfirmSignIn,
	AmplifyConfirmSignUp,
	AmplifyContainer,
	AmplifyCountryDialCode,
	AmplifyEmailField,
	AmplifyFacebookButton,
	AmplifyFederatedButtons,
	AmplifyFederatedSignIn,
	AmplifyForgotPassword,
	AmplifyFormField,
	AmplifyFormSection,
	AmplifyGoogleButton,
	AmplifyGreetings,
	AmplifyHint,
	AmplifyIcon,
	AmplifyIconButton,
	AmplifyInput,
	AmplifyLabel,
	AmplifyLink,
	AmplifyLoadingSpinner,
	AmplifyNav,
	AmplifyOauthButton,
	AmplifyPasswordField,
	AmplifyPhoneField,
	AmplifyPhotoPicker,
	AmplifyPicker,
	AmplifyRadioButton,
	AmplifyRequireNewPassword,
	AmplifyS3Album,
	AmplifyS3Image,
	AmplifyS3ImagePicker,
	AmplifyS3Text,
	AmplifyS3TextPicker,
	AmplifySection,
	AmplifySelect,
	AmplifySelectMfaType,
	AmplifySignIn,
	AmplifySignInButton,
	AmplifySignOut,
	AmplifySignUp,
	AmplifyStrike,
	AmplifyToast,
	AmplifyTooltip,
	AmplifyTotpSetup,
	AmplifyUsernameField,
	AmplifyVerifyContact,
];

@NgModule({
	declarations: DECLARATIONS,
	exports: DECLARATIONS,
	imports: [],
	providers: [],
})
export class AmplifyUIAngularModule {}
