// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

export const DEFAULT_REST_IAM_SIGNING_SERVICE = 'execute-api';

export const DEFAULT_APPSYNC_API_SERVICE = 'appsync-api';

export const DEFAULT_IAM_SIGNING_REGION = 'us-east-1';

/**
 * The REST endpoints generated by API Gateway
 * @see {@link https://docs.aws.amazon.com/general/latest/gr/apigateway.html#apigateway_region_data_plane}
 */
export const APIG_HOSTNAME_PATTERN =
	/^.+\.([a-z0-9-]+)\.([a-z0-9-]+)\.amazonaws\.com/;
