name: Bug report
description: Create a report to help us improve Amplify JS

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Try to include as much information as you can.
  - type: markdown
    attributes:
      value: |
        For reference, the current versions of the Amplify JS packages are listed below. Please verify your issue against the latest version(s) of the relevant package(s).

        You can find information in our docs site regarding [Upgrading Amplify packages](https://docs.amplify.aws/lib/troubleshooting/upgrading/q/platform/js).

        <details>
          <summary>Click to expand package version list</summary>

          | Package                         | Version                                                                                                                                          |
          | ------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------ |
          | `amazon-cognito-identity-js`    | [![version](https://img.shields.io/npm/v/amazon-cognito-identity-js/latest.svg)](https://www.npmjs.com/package/amazon-cognito-identity-js)       |
          | `aws-amplify`                   | [![version](https://img.shields.io/npm/v/aws-amplify/latest.svg)](https://www.npmjs.com/package/aws-amplify)                                     |
          | `@aws-amplify/analytics`        | [![version](https://img.shields.io/npm/v/@aws-amplify/analytics/latest.svg)](https://www.npmjs.com/package/@aws-amplify/analytics)               |
          | `@aws-amplify/api`              | [![version](https://img.shields.io/npm/v/@aws-amplify/api/latest.svg)](https://www.npmjs.com/package/@aws-amplify/api)                           |
          | `@aws-amplify/api-graphql`      | [![version](https://img.shields.io/npm/v/@aws-amplify/api-graphql/latest.svg)](https://www.npmjs.com/package/@aws-amplify/api-graphql)           |
          | `@aws-amplify/api-rest`         | [![version](https://img.shields.io/npm/v/@aws-amplify/api-rest/latest.svg)](https://www.npmjs.com/package/@aws-amplify/api-rest)                 |
          | `@aws-amplify/auth`             | [![version](https://img.shields.io/npm/v/@aws-amplify/auth/latest.svg)](https://www.npmjs.com/package/@aws-amplify/auth)                         |
          | `@aws-amplify/core`             | [![version](https://img.shields.io/npm/v/@aws-amplify/core/latest.svg)](https://www.npmjs.com/package/@aws-amplify/core)                         |
          | `@aws-amplify/datastore`        | [![version](https://img.shields.io/npm/v/@aws-amplify/datastore/latest.svg)](https://www.npmjs.com/package/@aws-amplify/datastore)               |
          | `@aws-amplify/interactions`     | [![version](https://img.shields.io/npm/v/@aws-amplify/interactions/latest.svg)](https://www.npmjs.com/package/@aws-amplify/interactions)         |
          | `@aws-amplify/predictions`      | [![version](https://img.shields.io/npm/v/@aws-amplify/predictions/latest.svg)](https://www.npmjs.com/package/@aws-amplify/predictions)           |
          | `@aws-amplify/pubsub`           | [![version](https://img.shields.io/npm/v/@aws-amplify/pubsub/latest.svg)](https://www.npmjs.com/package/@aws-amplify/pubsub)                     |
          | `@aws-amplify/storage`          | [![version](https://img.shields.io/npm/v/@aws-amplify/storage/latest.svg)](https://www.npmjs.com/package/@aws-amplify/storage)                   |

        </details>

  - type: checkboxes
    attributes:
      label: |
        Before opening, please confirm:
      options:
        - label: I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
          required: true
        - label: I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
          required: true
        - label: I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
          required: true

  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: dropdown
    attributes:
      label: JavaScript Framework
      description: What JavaScript framework is being used?
      multiple: true
      options:
        - Angular
        - React
        - React Native
        - Vue
        - Web Components
        - Next.js
        - Not applicable
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Amplify APIs
      description: |
        What [Amplify APIs](https://docs.amplify.aws/lib/q/platform/js) are being used?
      multiple: true
      options:
        - Authentication
        - Analytics
        - REST API
        - GraphQL API
        - DataStore
        - Storage
        - Geo
        - Push Notifications
        - Interactions
        - PubSub
        - Internationalization
        - Cache
        - Predictions
        - Not applicable
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Amplify Version
      description: |
        Which major version of `aws-amplify` are you using?
      multiple: false
      options:
        - v6
        - v5
        - Older than v5
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Amplify Categories
      description: |
        What [Amplify categories](https://github.com/aws-amplify/amplify-cli#category-specific-commands) are being used?
      multiple: true
      options:
        - auth
        - storage
        - geo
        - function
        - api
        - analytics
        - hosting
        - notifications
        - interactions
        - predictions
        - Not applicable
  - type: dropdown
    attributes:
      label: Backend
      description: |
        How have you deployed the backend resources?
      multiple: false
      options:
        - Amplify CLI
        - Amplify Gen 2 (Preview)
        - CDK
        - Other
  - type: textarea
    attributes:
      label: Environment information
      description: |
        Please run the following command inside your project and copy/paste the output below:
        ```
        npx envinfo --system --binaries --browsers --npmPackages --duplicates --npmGlobalPackages
        ```
      value: |
        <details>

        ```
        # Put output below this line


        ```

        </details>
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Details
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction steps
      description: |
        How do you trigger this bug? Please walk us through it step by step. Screenshots can be attached in textarea below.
      placeholder: |
        1. Install '...'
        2. Configure '...'
        3. Go to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Code Snippet
      description: |
        Please provide a code snippet or a link to sample code of the issue you are experiencing to help us reproduce the issue.

        **Be sure to remove any sensitive data.**
      value: |
        ```javascript
        // Put your code below this line.

        ```
  - type: textarea
    attributes:
      label: Log output
      description: |
        For example, error messages, or stack traces.

        You can turn on the debug mode to provide more info for us
        by using the below statement in your app.

        ```javascript
        window.LOG_LEVEL = 'DEBUG';
        ```
        **Be sure to remove any sensitive data.**
      value: |
        <details>

        ```
        // Put your logs below this line


        ```

        </details>
  - type: markdown
    attributes:
      value: |
        ## Configuration
  - type: textarea
    attributes:
      label: aws-exports.js
      description: If applicable, please provide your `aws-exports.js` file.
      placeholder: |
        ```javascript
          const awsmobile = {
              "aws_project_region": "us-east-1",
              "aws_cognito_identity_pool_id": "us-east-1:xxx-xxxx-xxxx-xxxx-xxxxxxxx",
              "aws_cognito_region": "us-east-1",
              "aws_user_pools_id": "us-east-1_xxx",
              "aws_user_pools_web_client_id": "xxxx",
              "oauth": {}
          };
        ```
  - type: textarea
    attributes:
      label: Manual configuration
      description: If applicable, please provide your **manual configuration** example.
      placeholder: |
        ```json
          {
            Auth: {
                identityPoolId: 'XX-XXXX-X:XXXXXXXX-XXXX-1234-abcd-1234567890ab',
                region: 'XX-XXXX-X',
                identityPoolRegion: 'XX-XXXX-X',
                userPoolId: 'XX-XXXX-X_abcd1234',
                userPoolWebClientId: 'a1b2c3d4e5f6g7h8i9j0k1l2m3',
                mandatorySignIn: false,
                authenticationFlowType: 'USER_PASSWORD_AUTH',
                oauth: {
                    domain: 'your_cognito_domain',
                    scope: ['phone', 'email', 'profile', 'openid', 'aws.cognito.signin.user.admin'],
                    redirectSignIn: 'http://localhost:3000/',
                    redirectSignOut: 'http://localhost:3000/',
                    responseType: 'code' // or 'token', note that REFRESH token will only be generated when the responseType is code
                  }
              }
          }
        ```
  - type: textarea
    attributes:
      label: Additional configuration
      description: |
        If applicable, provide more configuration data.

        For example, for Amazon Cognito, run `aws cognito-idp describe-user-pool --user-pool-id us-west-2_xxxxxx`.

        **Be sure to remove any sensitive data**

      placeholder: |
        ```json


        ```
  - type: markdown
    attributes:
      value: |
        ## Smartphone (Optional)
  - type: input
    attributes:
      label: Mobile Device
      description: e.g. iPhone6
  - type: input
    attributes:
      label: Mobile Operating System
      description: For example, iOS8.1
  - type: input
    attributes:
      label: Mobile Browser
      description: For example, stock browser, Safari, Chrome
  - type: input
    attributes:
      label: Mobile Browser Version
      description: For example, 22
  - type: textarea
    attributes:
      label: Additional information and screenshots
      description: |
        If you have any additional information (i.e. `package.json`), workarounds, etc. for us, use the field below.
        Please note, you can attach screenshots or screen recordings here, by
        dragging and dropping files in the field below.
