name: Setup Amplify Integration Test Package
description: Checks out "amplify-js-samples-staging" and builds the package with caching

inputs:
  GH_TOKEN_STAGING_READ:
    description: The token that grants read access to the sample staging repo
    required: true

runs:
  using: 'composite'
  steps:
    - name: Create cache
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      id: cache-samples-staging-build
      with:
        key: aws-amplify-js-samples-staging-build-${{ github.sha }}
        path: |
          ./amplify-js-samples-staging/node_modules
          /home/runner/.cache/Cypress
      env:
        SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
    - name: Checkout staging repo
      uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0 https://github.com/actions/checkout/commit/24cb9080177205b6e8c946b17badbe402adc938f
      with:
        repository: ${{ github.repository_owner }}/amplify-js-samples-staging
        path: amplify-js-samples-staging
        token: ${{ inputs.GH_TOKEN_STAGING_READ }}

    # We test on the staging branch that corresponds to the amplify-js branch
    #   when it exists and test on the default branch `main` otherwise
    - name: Staging repo branch selection
      shell: bash
      working-directory: ./amplify-js-samples-staging
      env:
        BRANCH: ${{ github.ref_name }}
      run: |
        if git ls-remote origin $BRANCH | grep -q refs/heads/$BRANCH$; then
            # Branch exists, checkout and echo success message
            git fetch origin $BRANCH
            git checkout $BRANCH
            echo "Checked out branch: $BRANCH"
        else
            # Branch doesn't exist, echo error message
            echo "Branch '$BRANCH' does not exist"
        fi

    - name: Install
      run: |
        yarn
      shell: bash
      working-directory: ./amplify-js-samples-staging
