export { AmplifyAngularModule } from './src/aws-amplify-angular.module';
export { AmplifyService}  from './src/providers/amplify.service';

// export { AmplifyIonicModule } from './aws-amplify-ionic-module';

// export { AuthenticatorComponent } from './components/authenticator/authenticator/authenticator.factory';
// export { AuthenticatorComponentCore } from './components/authenticator/authenticator/authenticator.component.core';
// export { ConfirmSignInComponent } from './components/authenticator/confirm-sign-in-component/confirm-sign-in.factory';
// export { ConfirmSignInComponentCore } from './components/authenticator/confirm-sign-in-component/confirm-sign-in-component.core';
// export { ConfirmSignUpComponent } from './components/authenticator/confirm-sign-up-component/confirm-sign-up.factory';
// export { ConfirmSignUpComponentCore } from './components/authenticator/confirm-sign-up-component/confirm-sign-up.component.core';
// export { SignInComponent } from './components/authenticator/sign-in-component/sign-in.component.factory';
// export { SignInComponentCore } from './components/authenticator/sign-in-component/sign-in.component.core';
// export { SignUpComponent } from './components/authenticator/sign-up-component/sign-up.factory';
// export { SignUpComponentCore } from './components/authenticator/sign-up-component/sign-up.component.core';
// export { RequireNewPasswordComponent } from './components/authenticator/require-new-password-component/require-new-password.factory';
// export { RequireNewPasswordComponentCore } from './components/authenticator/require-new-password-component/require-new-password.component.core';
// export { GreetingComponent } from './components/authenticator/greeting-component/greeting.factory';
// export { GreetingComponentCore } from './components/authenticator/greeting-component/greeting.component.core';
// export { ForgotPasswordComponent } from './components/authenticator/forgot-password-component/forgot-password.factory';
// export { ForgotPasswordComponentCore } from './components/authenticator/forgot-password-component/forgot-password.component.core';
// export { S3AlbumComponent } from './components/storage/s3-album-component/s3-album.factory';
// export { S3AlbumComponentCore } from './components/storage/s3-album-component/s3-album.component.core';
// export { S3ImageComponent } from './components/storage/s3-image-component/s3-image.factory';
// export { S3ImageComponentCore } from './components/storage/s3-image-component/s3-image.component.core';
// export { PhotoPickerComponent } from './components/storage/photo-picker-component/photo-picker.factory';
// export { PhotoPickerComponentCore } from './components/storage/photo-picker-component/photo-picker.component.core';
// export { ChatBotComponent } from './components/interactions/chatbot/chatbot.factory';
// export { ChatbotComponentCore } from './components/interactions/chatbot/chatbot.component.core'; 
// export { DynamicComponentDirective } from './directives/dynamic.component.directive';
// export { FormComponent } from './components/common/form.component';

// export { AuthenticatorIonicComponent } from './components/authenticator/authenticator/authenticator.component.ionic';
// export { ConfirmSignInComponentIonic } from './components/authenticator/confirm-sign-in-component/confirm-sign-in-component.ionic';
// export { ConfirmSignUpComponentIonic } from './components/authenticator/confirm-sign-up-component/confirm-sign-up.component.ionic';
// export { ForgotPasswordComponentIonic } from './components/authenticator/forgot-password-component/forgot-password.component.ionic';
// export { GreetingComponentIonic } from './components/authenticator/greeting-component/greeting.component.ionic';
// export { SignInComponentIonic } from './components/authenticator/sign-in-component/sign-in.component.ionic';
// export { SignUpComponentIonic } from './components/authenticator/sign-up-component/sign-up.component.ionic';
// export { RequireNewPasswordComponentIonic } from './components/authenticator/require-new-password-component/require-new-password.component.ionic';
// export { PhotoPickerIonicComponent } from './components/storage/photo-picker-component/photo-picker.component.ionic';
// export { S3AlbumComponentIonic } from './components/storage/s3-album-component/s3-album.component.ionic';
// export { S3ImageComponentIonic } from './components/storage/s3-image-component/s3-image.component.ionic';
// export { ChatbotComponentIonic } from './components/interactions/chatbot/chatbot.component.ionic';