/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  SelectOptions,
} from './components/amplify-select/amplify-select-interface';

export namespace Components {
  interface AmplifyAuthenticator {
    'content': Function;
    'override': boolean;
    'signIn': Function;
  }
  interface AmplifyButton {
    'role': string;
    'styleOverride': boolean;
    'type': string;
  }
  interface AmplifyCheckbox {
    /**
    * Field ID used for the 'htmlFor' in the label
    */
    'fieldId': string;
    /**
    * Label for the checkbox
    */
    'label': string;
    /**
    * Name of the checkbox
    */
    'name'?: string;
    /**
    * (optional) Whether or not to override default styling
    */
    'styleOverride'?: boolean;
    /**
    * Default to checkbox
    */
    'type': string;
    /**
    * Value of the checkbox
    */
    'value'?: string;
  }
  interface AmplifyExamples {}
  interface AmplifyFormField {
    'fieldId': string;
    'hint': string | null;
    'label': string | null;
    'styleOverride': boolean;
  }
  interface AmplifyHint {
    'styleOverride': boolean;
  }
  interface AmplifyLabel {
    'htmlFor': string;
    'styleOverride': boolean;
  }
  interface AmplifyLink {
    'role': string;
    'styleOverride': boolean;
  }
  interface AmplifyRadioButton {
    /**
    * Field ID used for the 'for' in the label
    */
    'fieldId': string;
    /**
    * Label for the radio button
    */
    'label': string;
    /**
    * (optional) Name of radio button
    */
    'name'?: string;
    /**
    * (optional) Whether or not to override default styling
    */
    'styleOverride'?: boolean;
    /**
    * Type of input for this component is radio
    */
    'type': string;
    /**
    * (optional) Value of radio button
    */
    'value'?: string;
  }
  interface AmplifySceneLoading {
    'loadPercentage': number;
    'sceneError': object;
    'sceneName': string;
  }
  interface AmplifySection {
    'role': string;
    'styleOverride': boolean;
  }
  interface AmplifySectionHeader {
    'styleOverride': boolean;
  }
  interface AmplifySelect {
    /**
    * Must be an Array of Objects with an Object shape of {label: string, value: string|number}
    */
    'options'?: SelectOptions;
    /**
    * (Optional) Overrides default styling
    */
    'styleOverride': boolean;
  }
  interface AmplifySignIn {
    'handleSubmit': (Event) => void;
    'styleOverride': boolean;
    'validationErrors': string;
  }
  interface AmplifySignInPasswordField {
    'component': Function;
    'description': string | null;
    'fieldId': string;
    'hint': string | null;
    'inputProps': {
      type?: string;
      onChange?: (Event) => void;
    };
    'label': string | null;
  }
  interface AmplifySignInUsernameField {
    'component': Function;
    'description': string | null;
    'fieldId': string;
    'hint': string | null;
    'inputProps': {
      type?: string;
      onChange?: (Event) => void;
    };
    'label': string | null;
  }
  interface AmplifyTextField {
    'description': string | null;
    'fieldId': string;
    'inputProps': {
      type?: string;
      onInput?: (Event) => void;
    };
    'label': string | null;
  }
  interface AmplifyTextInput {
    'fieldId': string;
    'inputProps': {
      placeholder?: string;
      type?: string;
      onInput?: (Event) => void;
    };
    'styleOverride': boolean;
  }
  interface RockPaperScissor {
    'icon': Function;
  }
}

declare global {


  interface HTMLAmplifyAuthenticatorElement extends Components.AmplifyAuthenticator, HTMLStencilElement {}
  var HTMLAmplifyAuthenticatorElement: {
    prototype: HTMLAmplifyAuthenticatorElement;
    new (): HTMLAmplifyAuthenticatorElement;
  };

  interface HTMLAmplifyButtonElement extends Components.AmplifyButton, HTMLStencilElement {}
  var HTMLAmplifyButtonElement: {
    prototype: HTMLAmplifyButtonElement;
    new (): HTMLAmplifyButtonElement;
  };

  interface HTMLAmplifyCheckboxElement extends Components.AmplifyCheckbox, HTMLStencilElement {}
  var HTMLAmplifyCheckboxElement: {
    prototype: HTMLAmplifyCheckboxElement;
    new (): HTMLAmplifyCheckboxElement;
  };

  interface HTMLAmplifyExamplesElement extends Components.AmplifyExamples, HTMLStencilElement {}
  var HTMLAmplifyExamplesElement: {
    prototype: HTMLAmplifyExamplesElement;
    new (): HTMLAmplifyExamplesElement;
  };

  interface HTMLAmplifyFormFieldElement extends Components.AmplifyFormField, HTMLStencilElement {}
  var HTMLAmplifyFormFieldElement: {
    prototype: HTMLAmplifyFormFieldElement;
    new (): HTMLAmplifyFormFieldElement;
  };

  interface HTMLAmplifyHintElement extends Components.AmplifyHint, HTMLStencilElement {}
  var HTMLAmplifyHintElement: {
    prototype: HTMLAmplifyHintElement;
    new (): HTMLAmplifyHintElement;
  };

  interface HTMLAmplifyLabelElement extends Components.AmplifyLabel, HTMLStencilElement {}
  var HTMLAmplifyLabelElement: {
    prototype: HTMLAmplifyLabelElement;
    new (): HTMLAmplifyLabelElement;
  };

  interface HTMLAmplifyLinkElement extends Components.AmplifyLink, HTMLStencilElement {}
  var HTMLAmplifyLinkElement: {
    prototype: HTMLAmplifyLinkElement;
    new (): HTMLAmplifyLinkElement;
  };

  interface HTMLAmplifyRadioButtonElement extends Components.AmplifyRadioButton, HTMLStencilElement {}
  var HTMLAmplifyRadioButtonElement: {
    prototype: HTMLAmplifyRadioButtonElement;
    new (): HTMLAmplifyRadioButtonElement;
  };

  interface HTMLAmplifySceneLoadingElement extends Components.AmplifySceneLoading, HTMLStencilElement {}
  var HTMLAmplifySceneLoadingElement: {
    prototype: HTMLAmplifySceneLoadingElement;
    new (): HTMLAmplifySceneLoadingElement;
  };

  interface HTMLAmplifySectionElement extends Components.AmplifySection, HTMLStencilElement {}
  var HTMLAmplifySectionElement: {
    prototype: HTMLAmplifySectionElement;
    new (): HTMLAmplifySectionElement;
  };

  interface HTMLAmplifySectionHeaderElement extends Components.AmplifySectionHeader, HTMLStencilElement {}
  var HTMLAmplifySectionHeaderElement: {
    prototype: HTMLAmplifySectionHeaderElement;
    new (): HTMLAmplifySectionHeaderElement;
  };

  interface HTMLAmplifySelectElement extends Components.AmplifySelect, HTMLStencilElement {}
  var HTMLAmplifySelectElement: {
    prototype: HTMLAmplifySelectElement;
    new (): HTMLAmplifySelectElement;
  };

  interface HTMLAmplifySignInElement extends Components.AmplifySignIn, HTMLStencilElement {}
  var HTMLAmplifySignInElement: {
    prototype: HTMLAmplifySignInElement;
    new (): HTMLAmplifySignInElement;
  };

  interface HTMLAmplifySignInPasswordFieldElement extends Components.AmplifySignInPasswordField, HTMLStencilElement {}
  var HTMLAmplifySignInPasswordFieldElement: {
    prototype: HTMLAmplifySignInPasswordFieldElement;
    new (): HTMLAmplifySignInPasswordFieldElement;
  };

  interface HTMLAmplifySignInUsernameFieldElement extends Components.AmplifySignInUsernameField, HTMLStencilElement {}
  var HTMLAmplifySignInUsernameFieldElement: {
    prototype: HTMLAmplifySignInUsernameFieldElement;
    new (): HTMLAmplifySignInUsernameFieldElement;
  };

  interface HTMLAmplifyTextFieldElement extends Components.AmplifyTextField, HTMLStencilElement {}
  var HTMLAmplifyTextFieldElement: {
    prototype: HTMLAmplifyTextFieldElement;
    new (): HTMLAmplifyTextFieldElement;
  };

  interface HTMLAmplifyTextInputElement extends Components.AmplifyTextInput, HTMLStencilElement {}
  var HTMLAmplifyTextInputElement: {
    prototype: HTMLAmplifyTextInputElement;
    new (): HTMLAmplifyTextInputElement;
  };

  interface HTMLRockPaperScissorElement extends Components.RockPaperScissor, HTMLStencilElement {}
  var HTMLRockPaperScissorElement: {
    prototype: HTMLRockPaperScissorElement;
    new (): HTMLRockPaperScissorElement;
  };
  interface HTMLElementTagNameMap {
    'amplify-authenticator': HTMLAmplifyAuthenticatorElement;
    'amplify-button': HTMLAmplifyButtonElement;
    'amplify-checkbox': HTMLAmplifyCheckboxElement;
    'amplify-examples': HTMLAmplifyExamplesElement;
    'amplify-form-field': HTMLAmplifyFormFieldElement;
    'amplify-hint': HTMLAmplifyHintElement;
    'amplify-label': HTMLAmplifyLabelElement;
    'amplify-link': HTMLAmplifyLinkElement;
    'amplify-radio-button': HTMLAmplifyRadioButtonElement;
    'amplify-scene-loading': HTMLAmplifySceneLoadingElement;
    'amplify-section': HTMLAmplifySectionElement;
    'amplify-section-header': HTMLAmplifySectionHeaderElement;
    'amplify-select': HTMLAmplifySelectElement;
    'amplify-sign-in': HTMLAmplifySignInElement;
    'amplify-sign-in-password-field': HTMLAmplifySignInPasswordFieldElement;
    'amplify-sign-in-username-field': HTMLAmplifySignInUsernameFieldElement;
    'amplify-text-field': HTMLAmplifyTextFieldElement;
    'amplify-text-input': HTMLAmplifyTextInputElement;
    'rock-paper-scissor': HTMLRockPaperScissorElement;
  }
}

declare namespace LocalJSX {
  interface AmplifyAuthenticator extends JSXBase.HTMLAttributes<HTMLAmplifyAuthenticatorElement> {
    'content'?: Function;
    'onAuthStateChange'?: (event: CustomEvent<any>) => void;
    'override'?: boolean;
    'signIn'?: Function;
  }
  interface AmplifyButton extends JSXBase.HTMLAttributes<HTMLAmplifyButtonElement> {
    'role'?: string;
    'styleOverride'?: boolean;
    'type'?: string;
  }
  interface AmplifyCheckbox extends JSXBase.HTMLAttributes<HTMLAmplifyCheckboxElement> {
    /**
    * Field ID used for the 'htmlFor' in the label
    */
    'fieldId'?: string;
    /**
    * Label for the checkbox
    */
    'label'?: string;
    /**
    * Name of the checkbox
    */
    'name'?: string;
    /**
    * (optional) Whether or not to override default styling
    */
    'styleOverride'?: boolean;
    /**
    * Default to checkbox
    */
    'type'?: string;
    /**
    * Value of the checkbox
    */
    'value'?: string;
  }
  interface AmplifyExamples extends JSXBase.HTMLAttributes<HTMLAmplifyExamplesElement> {}
  interface AmplifyFormField extends JSXBase.HTMLAttributes<HTMLAmplifyFormFieldElement> {
    'fieldId'?: string;
    'hint'?: string | null;
    'label'?: string | null;
    'styleOverride'?: boolean;
  }
  interface AmplifyHint extends JSXBase.HTMLAttributes<HTMLAmplifyHintElement> {
    'styleOverride'?: boolean;
  }
  interface AmplifyLabel extends JSXBase.HTMLAttributes<HTMLAmplifyLabelElement> {
    'htmlFor'?: string;
    'styleOverride'?: boolean;
  }
  interface AmplifyLink extends JSXBase.HTMLAttributes<HTMLAmplifyLinkElement> {
    'role'?: string;
    'styleOverride'?: boolean;
  }
  interface AmplifyRadioButton extends JSXBase.HTMLAttributes<HTMLAmplifyRadioButtonElement> {
    /**
    * Field ID used for the 'for' in the label
    */
    'fieldId'?: string;
    /**
    * Label for the radio button
    */
    'label'?: string;
    /**
    * (optional) Name of radio button
    */
    'name'?: string;
    /**
    * (optional) Whether or not to override default styling
    */
    'styleOverride'?: boolean;
    /**
    * Type of input for this component is radio
    */
    'type'?: string;
    /**
    * (optional) Value of radio button
    */
    'value'?: string;
  }
  interface AmplifySceneLoading extends JSXBase.HTMLAttributes<HTMLAmplifySceneLoadingElement> {
    'loadPercentage'?: number;
    'sceneError'?: object;
    'sceneName'?: string;
  }
  interface AmplifySection extends JSXBase.HTMLAttributes<HTMLAmplifySectionElement> {
    'role'?: string;
    'styleOverride'?: boolean;
  }
  interface AmplifySectionHeader extends JSXBase.HTMLAttributes<HTMLAmplifySectionHeaderElement> {
    'styleOverride'?: boolean;
  }
  interface AmplifySelect extends JSXBase.HTMLAttributes<HTMLAmplifySelectElement> {
    /**
    * Must be an Array of Objects with an Object shape of {label: string, value: string|number}
    */
    'options'?: SelectOptions;
    /**
    * (Optional) Overrides default styling
    */
    'styleOverride'?: boolean;
  }
  interface AmplifySignIn extends JSXBase.HTMLAttributes<HTMLAmplifySignInElement> {
    'handleSubmit'?: (Event) => void;
    'styleOverride'?: boolean;
    'validationErrors'?: string;
  }
  interface AmplifySignInPasswordField extends JSXBase.HTMLAttributes<HTMLAmplifySignInPasswordFieldElement> {
    'component'?: Function;
    'description'?: string | null;
    'fieldId'?: string;
    'hint'?: string | null;
    'inputProps'?: {
      type?: string;
      onChange?: (Event) => void;
    };
    'label'?: string | null;
  }
  interface AmplifySignInUsernameField extends JSXBase.HTMLAttributes<HTMLAmplifySignInUsernameFieldElement> {
    'component'?: Function;
    'description'?: string | null;
    'fieldId'?: string;
    'hint'?: string | null;
    'inputProps'?: {
      type?: string;
      onChange?: (Event) => void;
    };
    'label'?: string | null;
  }
  interface AmplifyTextField extends JSXBase.HTMLAttributes<HTMLAmplifyTextFieldElement> {
    'description'?: string | null;
    'fieldId'?: string;
    'inputProps'?: {
      type?: string;
      onInput?: (Event) => void;
    };
    'label'?: string | null;
  }
  interface AmplifyTextInput extends JSXBase.HTMLAttributes<HTMLAmplifyTextInputElement> {
    'fieldId'?: string;
    'inputProps'?: {
      placeholder?: string;
      type?: string;
      onInput?: (Event) => void;
    };
    'styleOverride'?: boolean;
  }
  interface RockPaperScissor extends JSXBase.HTMLAttributes<HTMLRockPaperScissorElement> {
    'icon'?: Function;
    'onIconChange'?: (event: CustomEvent<any>) => void;
  }

  interface IntrinsicElements {
    'amplify-authenticator': AmplifyAuthenticator;
    'amplify-button': AmplifyButton;
    'amplify-checkbox': AmplifyCheckbox;
    'amplify-examples': AmplifyExamples;
    'amplify-form-field': AmplifyFormField;
    'amplify-hint': AmplifyHint;
    'amplify-label': AmplifyLabel;
    'amplify-link': AmplifyLink;
    'amplify-radio-button': AmplifyRadioButton;
    'amplify-scene-loading': AmplifySceneLoading;
    'amplify-section': AmplifySection;
    'amplify-section-header': AmplifySectionHeader;
    'amplify-select': AmplifySelect;
    'amplify-sign-in': AmplifySignIn;
    'amplify-sign-in-password-field': AmplifySignInPasswordField;
    'amplify-sign-in-username-field': AmplifySignInUsernameField;
    'amplify-text-field': AmplifyTextField;
    'amplify-text-input': AmplifyTextInput;
    'rock-paper-scissor': RockPaperScissor;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


