import {
	GetObjectCommandInput,
	GetObjectCommandOutput,
	ListObjectsV2CommandInput,
	ListObjectsV2CommandOutput,
	PutObjectCommandInput,
	PutObjectCommandOutput,
	CreateMultipartUploadCommandInput,
	CreateMultipartUploadCommandOutput,
	AbortMultipartUploadCommandInput,
	AbortMultipartUploadCommandOutput,
	CompleteMultipartUploadCommandInput,
	CompleteMultipartUploadCommandOutput,
	UploadPartCommandInput,
	UploadPartCommandOutput,
	ListPartsCommandInput,
	ListPartsCommandOutput,
	CopyObjectCommandInput,
	CopyObjectCommandOutput,
	HeadObjectCommandInput,
	HeadObjectCommandOutput,
	DeleteObjectCommandInput,
} from '@aws-sdk/client-s3';

export {
	GetObjectCommandInput,
	GetObjectCommandOutput,
	ListObjectsV2CommandInput,
	ListObjectsV2CommandOutput,
	PutObjectCommandInput,
	PutObjectCommandOutput,
	CreateMultipartUploadCommandInput,
	CreateMultipartUploadCommandOutput,
	AbortMultipartUploadCommandInput,
	AbortMultipartUploadCommandOutput,
	CompleteMultipartUploadCommandInput,
	CompleteMultipartUploadCommandOutput,
	UploadPartCommandInput,
	UploadPartCommandOutput,
	ListPartsCommandInput,
	ListPartsCommandOutput,
	CopyObjectCommandInput,
	CopyObjectCommandOutput,
	HeadObjectCommandInput,
	HeadObjectCommandOutput,
	DeleteObjectCommandInput,
};
