// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

export enum StateMachineHubEventName {
	AUTH_EVENT_ADDED = 'AUTH_EVENT_ADDED',
	CURRENT_STATE_REQUESTED = 'CURRENT_STATE_REQUESTED',
	NEXT_STATE_NOT_FOUND = 'NEXT_STATE_NOT_FOUND',
	NULL_TRANSITION = 'NULL_TRANSITION',
	STATE_GUARD_FAILURE = 'STATE_GUARD_FAILURE',
	STATE_TRANSITION = 'STATE_TRANSITION',
}
