// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:34a9e798-361d-4592-af76-f44eed2f6318",
    "aws_cognito_region": "us-east-1",
    "oauth": {},
    "XR": {
        "scenes": {
            "classroom": {
                "sceneConfig": {
                    "sceneId": "3fdcdff250764294935f2534726f32d4.scene",
                    "region": "us-east-1",
                    "projectName": "Drafts-assumed-role/Admin/jranz-Isengard",
                    "url": "https://sumerian.us-east-1.amazonaws.com/20180801/projects/Drafts-assumed-role%2FAdmin%2Fjranz-Isengard/release/authTokens?sceneId=3fdcdff250764294935f2534726f32d4.scene"
                }
            }
        }
    }
};


export default awsmobile;
