const errors = {
    trackLifeCycle44Analytics: "No Analytics module found, please ensure @aws-amplify/analytics is imported",
    trackUpdate32Analytics: "No Analytics module found, please ensure @aws-amplify/analytics is imported",
    _fethcData39APIGraphQLConnect: "No API module found, please ensure @aws-amplify/api is imported",
    federatedSignIn57AuthProviderWithAmazon: "No Auth module found, please ensure @aws-amplify/auth is imported",
    federatedSignIn59AuthProviderWithFacebook: "No Auth module found, please ensure @aws-amplify/auth is imported",
    federatedSignIn46AuthProviderWithGoogle: "No Auth module found, please ensure @aws-amplify/auth is imported",
    federatedSignIn19AuthProviderWithOAuth: "No Auth module found, please ensure @aws-amplify/auth is imported",
    checkUser48AuthAuthStateWrapper: "No Auth module found, please ensure @aws-amplify/auth is imported",
    checkContact47AuthConfirmSignIn: "No Auth module found, please ensure @aws-amplify/auth is imported",
    confirm66AuthConfirmSignIn: "No Auth module found, please ensure @aws-amplify/auth is imported",
    confirm48AuthConfirmSignUp: "No Auth module found, please ensure @aws-amplify/auth is imported",
    resend59AuthConfirmSignUp: "No Auth module found, please ensure @aws-amplify/auth is imported",
    render71AuthFederatedSignIn: "No Auth module found, please ensure @aws-amplify/auth is imported",
    render100AuthFederatedSignIn: "No Auth module found, please ensure @aws-amplify/auth is imported",
    send47AuthForgotPassword: "No Auth module found, please ensure @aws-amplify/auth is imported",
    submit60AuthForgotPassword: "No Auth module found, please ensure @aws-amplify/auth is imported",
    signOut55AuthGreetings: "No Auth module found, please ensure @aws-amplify/auth is imported",
    checkUser104AuthGreetings: "No Auth module found, please ensure @aws-amplify/auth is imported",
    checkContact44AuthRequireNewPassword: "No Auth module found, please ensure @aws-amplify/auth is imported",
    change62AuthRequireNewPassword: "No Auth module found, please ensure @aws-amplify/auth is imported",
    checkContact63AuthSignIn: "No Auth module found, please ensure @aws-amplify/auth is imported",
    signIn79AuthSignIn: "No Auth module found, please ensure @aws-amplify/auth is imported",
    signOut55AuthSignOut: "No Auth module found, please ensure @aws-amplify/auth is imported",
    checkUser104AuthSignOut: "No Auth module found, please ensure @aws-amplify/auth is imported",
    signUp42AuthSignUp: "No Auth module found, please ensure @aws-amplify/auth is imported",
    checkContact45AuthTOTPSetup: "No Auth module found, please ensure @aws-amplify/auth is imported",
    verify53AuthVerifyContact: "No Auth module found, please ensure @aws-amplify/auth is imported",
    submit68AuthVerifyContact: "No Auth module found, please ensure @aws-amplify/auth is imported",
    submit75InteractionsChatBox: "No Interactions module found, please ensure @aws-amplify/interactions is imported",
    componentDidMount113InteractionsChatBox: "No Interactions module found, please ensure @aws-amplify/interactions is imported",
    componentDidUpdate124InteractionsChatBox: "No Interactions module found, please ensure @aws-amplify/interactions is imported",
    handlePick79StorageS3Album: "No Storage module found, please ensure @aws-amplify/storage is imported",
    list151StorageS3Album: "No Storage module found, please ensure @aws-amplify/storage is imported",
    getImageSource42StorageS3Image: "No Storage module found, please ensure @aws-amplify/storage is imported",
    load66StorageS3Image: "No Storage module found, please ensure @aws-amplify/storage is imported",
    handlePick101StorageS3Image: "No Storage module found, please ensure @aws-amplify/storage is imported",
    getText43StorageS3Text: "No Storage module found, please ensure @aws-amplify/storage is imported",
    load71StorageS3Text: "No Storage module found, please ensure @aws-amplify/storage is imported",
    handlePick106StorageS3Text: "No Storage module found, please ensure @aws-amplify/storage is imported",
    verify79WidgetSelectMFAType: "No Auth module found, please ensure @aws-amplify/auth is imported",
    setup68WidgetTOTPSetupComp: "No Auth module found, please ensure @aws-amplify/auth is imported",
    verifyTotpToken86WidgetTOTPSetupComp: "No Auth module found, please ensure @aws-amplify/auth is imported",
    // react native
    showComponent75AuthAuthPiece: "You must implement showComponent(theme) and don't forget to set this._validAuthStates.",
    send66AuthForgotPassword: "Username cannot be empty",
    verify68AuthVerifyContact: "Neither Email nor Phone Number selected"
};
