name: Release to npm and update repository

on: workflow_call

jobs:
  deploy-prep:
    name: Prepare for release
    runs-on: ubuntu-latest
    steps:
      - name: Generate a temporary branch name for merge PR
        id: generate-branch-name
        run: |
          echo "BRANCH_NAME=temp/release-merge-$(date +%s)" >> "$GITHUB_OUTPUT"
    outputs:
      branch_name: ${{ steps.generate-branch-name.outputs.BRANCH_NAME }}

  deploy:
    name: Publish to Amplify Package
    runs-on: ubuntu-latest
    needs: deploy-prep
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          path: amplify-js
          token: ${{ secrets.GH_TOKEN_AMPLIFY_JS_WRITE }}
          # Minimal depth 0 so we can fetch all git tags.
          fetch-depth: 0

      - name: Setup node and build the repository
        uses: ./amplify-js/.github/actions/node-and-build

      - name: Run npm publish
        uses: ./amplify-js/.github/actions/npm-publish
        with:
          target: release
          npm_token: ${{ secrets.NPM_TOKEN }}
          github_user: ${{ vars.GH_USER}}
          github_email: ${{ vars.GH_EMAIL}}

      - name: Set github commit user
        env:
          GITHUB_EMAIL: ${{ vars.GH_EMAIL }}
          GITHUB_USER: ${{ vars.GH_USER }}
        run: |
          git config --global user.email $GITHUB_EMAIL
          git config --global user.name $GITHUB_USER

      - name: Update roll-back infrastructure
        working-directory: ./amplify-js
        run: |
          git pull origin release
          PUBLISH_COMMIT_HASH=$(git log -n 1 --pretty=format:"%H")
          RELEASE_COMMIT_MESSAGE=$(git log -n 1 --skip 1 --pretty=oneline)
          if [[ $RELEASE_COMMIT_MESSAGE = *release\(required\)* ]]; then git tag -f required-release $PUBLISH_COMMIT_HASH; fi

      - name: Update API documentation
        working-directory: ./amplify-js
        run: |
          yarn run docs
          git add ./docs/api/
          git commit -m "chore(release): update API docs [skip release]"

      - name: Push post release changes to the release branch
        working-directory: ./amplify-js
        run: |
          git push origin release
          if [ $(git tag -l "required-release") ]; then git push -f origin required-release; fi

      - name: Create a PR to merge temporary release branch into main development branch
        working-directory: ./amplify-js
        env:
          TEMP_BRANCH_NAME: ${{ needs.deploy-prep.outputs.branch_name }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_AMPLIFY_JS_WRITE }}
        run: |
          git checkout -b $TEMP_BRANCH_NAME
          git push origin $TEMP_BRANCH_NAME
          gh pr create -B main -H $TEMP_BRANCH_NAME --title 'chore: Merge release into main' --body 'Merge the recently completed release back into the main development branch. Generated by the callable-npm-publish-release workflow.'          
