name: Build the API References and open a docs PR

on: workflow_call

jobs:
  docs-update-prep:
    name: Prepare for docs update
    runs-on: ubuntu-latest
    steps:
      - name: Generate a temporary branch name for docs update PR
        id: generate-branch-name
        run: |
          echo "BRANCH_NAME=temp/amplify-js-$(date +%s)" >> "$GITHUB_OUTPUT"
    outputs:
      branch_name: ${{ steps.generate-branch-name.outputs.BRANCH_NAME }}

  docs-update:
    name: Publish to amplify-js docs updates
    runs-on: ubuntu-latest
    needs: docs-update-prep
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          path: amplify-js
          # Minimal depth 0 so we can fetch all git tags.
          fetch-depth: 0
      - name: Checkout docs repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: ${{ github.repository_owner }}/docs
          path: docs
          token: ${{ secrets.GH_TOKEN_AMPLIFY_JS_WRITE }}

      - name: Setup node and build the repository
        uses: ./amplify-js/.github/actions/node-and-build

      - name: Set github commit user
        env:
          GITHUB_EMAIL: ${{ vars.GH_EMAIL }}
          GITHUB_USER: ${{ vars.GH_USER }}
        run: |
          git config --global user.email $GITHUB_EMAIL
          git config --global user.name $GITHUB_USER

      - name: Build docs references
        working-directory: ./amplify-js
        run: |
          yarn run docs:references

      - name: Prepare docs temp branch
        working-directory: ./docs
        env:
          TEMP_BRANCH_NAME: ${{ needs.docs-update-prep.outputs.branch_name }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_AMPLIFY_JS_WRITE }}
        run: |
          # First sync pre-prod/main with main using the "theirs" strategy to resolve conflicts
          git fetch origin main pre-prod/main
          git checkout pre-prod/main
          # Use -X theirs to automatically resolve conflicts in favor of main
          git merge origin/main --no-edit -X theirs --allow-unrelated-histories
          echo "MERGE COMPLETE"
          git push origin pre-prod/main
          
          # Now create a new branch from the updated pre-prod/main
          git checkout -b $TEMP_BRANCH_NAME

      - name: Setup yarn berry and Update API references
        working-directory: ./docs
        run: |
          npm install -g corepack
          corepack enable
          yarn -v

          # Update API references
          yarn && yarn clean-references -- -p amplify-js
          git add .
          git commit --allow-empty -m "chore: Update amplify-js API references"

      - name: Create a docs PR to merge api references back into the docs site
        working-directory: ./docs
        env:
          TEMP_BRANCH_NAME: ${{ needs.docs-update-prep.outputs.branch_name }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_AMPLIFY_JS_WRITE }}
        run: |
          git push origin $TEMP_BRANCH_NAME
          
          # Create PR from the temp branch to pre-prod/main
          gh pr create -B pre-prod/main -H $TEMP_BRANCH_NAME --title 'chore: amplify-js api references update' --body 'Merge the api references changes from the most recent release.'
