on:
  # Tests scheduled at 3pm(UTC) / 8am(PDT) everyday
  # default supported timezone is UTC
  schedule:
    - cron: '0 15 * * *'

jobs:
  canaries:
    secrets: inherit
    uses: ./.github/workflows/callable-canary-e2e.yml
