name: Version Packages

# Permissions required for creating pull requests
permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main
      - hotfix

jobs:
  # Create or update "Version Packages" PR
  # This job runs on every push to the branches specified above and creates/updates a PR with version bumps
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Check for changesets
        id: has-changesets
        uses: ./.github/actions/has-changesets

      - name: Setup Node.js
        if: steps.has-changesets.outputs.has-changesets == 'true'
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24

      - name: Install dependencies
        if: steps.has-changesets.outputs.has-changesets == 'true'
        run: yarn install --frozen-lockfile

      - name: Create Version Packages PR
        if: steps.has-changesets.outputs.has-changesets == 'true'
        uses: changesets/action@aba318e9165b45b7948c60273e0b72fce0a64eb9 # v1.4.7
        with:
          version: yarn changeset version
          commit: "chore(release): Version packages"
          title: 'Version Packages (${{ github.ref_name }})'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
