name: Set Node and Build
description: Checks out Amplify and builds the package
inputs:
  is-prebuild:
    required: false
    default: false
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version: 24
      env:
        SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
    - uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      id: cache-build-artifacts
      with:
        path: |
          **/node_modules
          **/dist
          **/lib
          **/lib-esm/
          **/es/
          **/esm/
          **/cjs/
          **/packages/core/src/Platform/version.ts
        key: ${{ runner.os }}-build-artifacts-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-build-artifacts-
      env:
        SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
    # TODO We should be able to skip yarn install if we cache enough things. Leaving because skipping causes issues.
    - name: Install
      if: inputs.is-prebuild != 'true' || steps.cache-build-artifacts.outputs.cache-hit != 'true'
      shell: bash
      working-directory: ./amplify-js
      run: |
        for i in {1..3}; do
          echo "Starting attempt $i."
          yarn && break
          echo "Attempt $i failed."
          sleep 5
        done
    - name: Build packages
      if: steps.cache-build-artifacts.outputs.cache-hit != 'true'
      run: yarn build
      shell: bash
      working-directory: ./amplify-js
